### ISSUE TITLE
Downloading options for ISIA Food-200

### ISSUE THREAD

**Issue by marcusklasson** [minweiqing/Ingredient-Guided-Cascaded-Multi-Attention-Network-for-Food-Recognition#1]
I was wondering if it would be possible to download the ISIA Food-200 dataset through another link than https://pan.baidu.com/s/1YWqvl1bDW0l1xpjHoxEkCg?

The links [image.rar] [metadata.rar] [readme.txt] simply takes you to https://www.google.com/?hl=zh_tw. 

For the other link https://pan.baidu.com/s/1YWqvl1bDW0l1xpjHoxEkCg, it is possible to download the dataset if you have an account on Baidu Cloud. However, I wasn't allowed to use my country code when I had to register my phone number. So would it be possible to make the dataset accessible through the links [image.rar] [metadata.rar] [readme.txt] ?

**Comment by minweiqing** [comment]
You can download the dataset from the following website:

http://123.57.42.89/FoodComputing__Dataset_files/FoodComputing__ISIA200.html


Best Regards
Weiqing



Key Laboratory of Intelligent Information Processing, the Institute of Computing Technology, Chinese Academy of Sciences, Beijing, China.
Address :No.6 Kexueyuan South Road Zhongguancun,Haidian District Beijing,China
 
From: Marcus Klasson
Date: 2020-06-23 17:11
To: minweiqing/Ingredient-Guided-Cascaded-Multi-Attention-Network-for-Food-Recognition
CC: Subscribed
Subject: [minweiqing/Ingredient-Guided-Cascaded-Multi-Attention-Network-for-Food-Recognition] Downloading options for ISIA Food-200 (#1)
I was wondering if it would be possible to download the ISIA Food-200 dataset through another link than https://pan.baidu.com/s/1YWqvl1bDW0l1xpjHoxEkCg?

**Comment by marcusklasson** [comment]
Thank you so much! 

Closing this issue.
